# Generated by Django 5.0.4 on 2024-05-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
    ]
