# Generated by Django 5.0.2 on 2024-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phone_brands',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='noname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(default='o', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.JSONField(default='o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='o', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.CharField(default='o', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(default=0.0005),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
