# Generated by Django 5.0.4 on 2024-05-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_product_battery_product_brand_product_cpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pin',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
