# Generated by Django 5.0.4 on 2024-05-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_pin_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.CASCADE, to='product.brand', to_field='name'),
        ),
    ]
