"""
Django settings for cdtt2 project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6w@ihst@+h(+&-=9la@m)!@k^^y7sw)(0_m2tag44y@j)mor3h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    
    'cdtt2',
    'product',
    'customer',
    'cart',
    'contact',

    'verify_email.apps.VerifyEmailConfig',
    'social_django',

    'admin_tools_stats',
]
#AUTHENTICATION_BACKENDS = ['customer.backends.EmailBackend']
AUTH_USER_MODEL = 'customer.Customer'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cdtt2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'cdtt2' / 'templates' / 'store',  # Đường dẫn tới thư mục templates của store
            BASE_DIR / 'cdtt2' / 'templates',  # Đường dẫn tới thư mục templates của admin
            BASE_DIR / 'cdtt2' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'cdtt2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'do_an_cdtt2',
        'USER': 'postgres',
        'PASSWORD': '0303',
        'HOST': 'localhost',  # or the IP address of your PostgreSQL server
        'PORT': '5432',  # or the port your PostgreSQL server is listening on
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
import os
STATIC_URL = '/statics/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'statics', 'store'),
    os.path.join(BASE_DIR, 'statics'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Đây là danh sách các backends xác thực mà Django sẽ sử dụng.
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'customer.backends.EmailBackend',
]
#Đây là thông tin cần thiết để xác thực người dùng thông qua Google OAuth2.
# Key và secret này được cung cấp bởi Google khi bạn đăng ký ứng dụng của mình với Google API.
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '394777303025-i2acku6kf3s0d2q1ec8clmsresk9g18l.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

LOGIN_URL = 'http://127.0.0.1:8000/'
LOGIN_REDIRECT_URL = 'http://127.0.0.1:8000/'
LOGOUT_URL = 'http://127.0.0.1:8000/'

#Đây là backend mà Django sẽ sử dụng để gửi email. Trong trường hợp này, nó sử dụng backend SMTP mặc định.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'trhaokiet.1303@gmail.com'
EMAIL_HOST_PASSWORD = 'afeodmcsajvyvrgn'