# Generated by Django 5.0.4 on 2024-05-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_customers_id_alter_cart_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='No address provided', max_length=200),
        ),
    ]
