# Generated by Django 5.0.5 on 2024-05-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ xác nhận', 'Đang chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Đang giao hàng', 'Đang giao hàng'), ('Đã giao thành công', 'Đã giao thành công')], default='Đang chờ xác nhận', max_length=50, null=True),
        ),
    ]
